title: Freddie Harrison
email: freddie@freddiewrit.es
description: >-
  Hello ðŸ‘‹ I'm Freddie Harrison. I'm a writer who cares about making things simple, accessible and a little more human.
url: 'https://freddiewrit.es'
timezone: Europe/London
permalink: /journal/:year/:slug/

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: tag
  permalinks:
    category: /tags/:name/

sass:
  sass_dir: _sass
  style: compressed
